spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8
      username: root
      password: 1234

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.lb.mall.entity